services:
  - type: web
    name: proposta-backend
    env: docker
    plan: free
    healthCheckPath: /
    dockerfilePath: ./Dockerfile

    envVars:
  - key: APP_KEY
    generateValue: true
  - key: JWT_SECRET
    generateValue: true
  - key: APP_DEBUG
    value: true
  - key: LOG_CHANNEL
    value: stderr
  - key: LOG_LEVEL
    value: debug

  # --- Configurações do Banco de Dados Netrevetech (MySQL) ---
  - key: DB_CONNECTION
    value: mysql
  - key: DB_HOST
    value: 151.243.218.177
  - key: DB_PORT
    value: 3306 
  - key: DB_DATABASE
    value: db-proposta
  - key: DB_USERNAME
    value: proposta
  - key: DB_PASSWORD
    value: proposta123